/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader, useThree } from '@react-three/fiber'
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry'
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader';
import * as THREE from 'three'
import helveticaRegular from 'three/examples/fonts/helvetiker_regular.typeface.json'

const deg2Rad = (deg: number) => {
  return deg * (Math.PI / 180)
}

export const MattyText = (props: any) => {
  const textMaterial = new THREE.MeshBasicMaterial({color: 'white'})
  let fontLoader = new FontLoader()
  const font = fontLoader.parse(helveticaRegular as any)
  const textGeometry = 
  new TextGeometry( "Matty Sun", {
		font: font,
		size: 1.5,
		depth: 0.25,
		curveSegments: 12,
		bevelEnabled: true,
		bevelThickness: 0,
		bevelSize: 0,
		bevelOffset: 0,
		bevelSegments: 0
	}  );
  
  return (
    <group {...props} dispose={null}>
      <directionalLight color="white" position={[0, 0, 6]} layers={1} />
      <mesh 
        position={[-4, -0.4, 5]}
        scale={1}
        geometry={textGeometry} 
        material={textMaterial}
        layers={1}
      />
    </group>
  )
}

useGLTF.preload('/models/scene-v1.glb')
