/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader, useThree } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import * as THREE from 'three'

export const Model = (props: any) => {
  const { camera } = useThree()
  camera.position.set(0, 1.5, 1.5); // Set position like this
  camera.lookAt(new THREE.Vector3(0, 0, 0)); // Set look at coordinate like this
  const gltf = useLoader(GLTFLoader, '/models/scene-v1.glb')
  const groupRef = useRef()
  const { nodes, materials, scene } = useGLTF('/models/scene-v1.glb')
  console.log(nodes)
  return (
    <group ref={groupRef} {...props} dispose={null}>
      {/* <mesh castShadow receiveShadow geometry={(nodes.Cloud__0 as THREE.Mesh).geometry} material={materials['Cloud__0']} /> */}
      <mesh castShadow receiveShadow geometry={(nodes.Sphere_sun_0 as THREE.Mesh).geometry} material={materials['material']} />
    </group>
  )
}

useGLTF.preload('/Poimandres.gltf')
